title = "Azure Saturday: Munich 2019"
baseURL = "https://azuresaturday.de"
languageCode = "en-us"
theme = "azuresaturday"
themesDir = "themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-23610381-2"
googleMapsAPIKey = "AIzaSyB3RO5oK8dNecMNetTCL9Bj1fSGb_g0n5o"
enableRobotsTXT = true

[[menu.main]]
    name = "> Tickets <"
    weight = -110
    identifier = "register"
    url = "https://www.eventbrite.de/e/azure-saturday-2019-registration-42274723837?ref=ebtn"	
    title = "Grab a free ticket (SOON)"
[[menu.main]]
    name = "Azure Saturday"
    weight = -130
    identifier = "Azure Saturday"
    url = "/"
    title = "Azure Saturday"
[params]
  register = "https://www.eventbrite.de/e/azure-saturday-2019-registration-42274723837?ref=ebtn"
  cfp = "https://sessionize.com/azure-saturday-2019"
  favicon = ""
  description = "​Azure Saturday Munich is a free community-focused Azure event dedicated to educating and engaging members of the local technical community. Azure Saturday draws upon the expertise of local Azure IT professionals, developers and solutions architects who come together to share their real world experiences, lessons learned, best practices, and general knowledge with other like-minded individuals."
  facebook = "https://facebook.com/azuresaturday"
  twitter = "https://twitter.com/azuresaturday"
  instagram = ""
  youtube = "https://www.youtube.com/watch?v=goIyXQNm3-4&t=17s"
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-blue"
  featured_image = "/img/logo.png"
  recent_posts_number = 2

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
